### ISSUE TITLE
Implement Sticky Navbar

### ISSUE THREAD

**Issue by Nunyaklah** [blackmann/stylebender#33]
Description:
Currently, the navbar in the project does not stick when users scroll, making it challenging to access certain functionalities such as changing color modes or downloading stylesheets. To improve the user experience, we need to implement a sticky navbar that remains fixed at the top of the page even during scrolling.

Expected Solution:
To address this issue, we need to add the functionality for the navbar to become sticky on scroll. This will allow users to access the navbar and its associated functionalities at all times, regardless of their position on the page.
@blackmann

**Comment by blackmann** [comment]
@Nunyaklah please go ahead
