### ISSUE TITLE
`:disabled` state for buttons

### ISSUE THREAD

**Issue by blackmann** [blackmann/stylebender#36]
Currently the buttons don't appear disabled when you add a disabled attribute to them. They appear and interact with the mouse as though they are clickable.

**Comment by 1nusah** [comment]
@blackmann aside cursor not allowed, which other styles are we looking at?

**Comment by blackmann** [comment]
The button should appear lighter

**Comment by 1nusah** [comment]
Alright, should changes be made in the css.ts file or app/src/components/Button.module.css

**Comment by blackmann** [comment]
`css.ts` <- That's where the style generation is done from

**Comment by 1nusah** [comment]
PR opened, please review
